# Generated by Django 4.0.4 on 2022-05-26 07:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_coursetopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetopic',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coursetopic',
            name='date',
            field=models.DateField(),
        ),
    ]
