# Generated by Django 4.0.4 on 2022-05-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_coursetopic_date_created_alter_coursetopic_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(to='project.course'),
        ),
    ]
