# Generated by Django 4.0.4 on 2022-06-27 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_student_user_alter_coursetopic_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
    ]
